name: Sync all github releases with erlang.org

## Update the base image every day
on:
  workflow_dispatch:
  schedule:
  ## In UTC
  - cron: '*/30 * * * *'

## Build base images to be used by other github workflows
jobs:

  # Wait for up to a minute for previous runs to complete, abort if not done by then
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-releases:
    if: github.repository == 'erlang/otp'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync releases
        run: >
          scripts/sync-github-releases.sh ${{ github.repository }}
          "Bearer ${{ secrets.GITHUB_TOKEN }}" "^2[123]\\..*" 25m
